rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  #jpa:
   # show-sql: true
   # hibernate:
   #   ddl-auto: none
   # database-platform: org.hibernate.dialect.H2Dialect

  #H2 DB Console Access
  h2:
    console:
      enabled: true

#Enable logging output for Spring Security
logging:
  level:
    org:
      springframework:
        security: TRACE


#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'