spring:
  #jpa:
   # show-sql: true
   # hibernate:
   #   ddl-auto: none
   # database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true


#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'